apiVersion: v1
kind: Service
metadata:
  name: spring-hotel-deploy
spec:
  selector: 
    hotel: spring 
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30031  
