apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-hotel-pvc
spec:
  volumeName: postgres-hotel-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi    
